---
title: "Exploratory Data Analysis"
author: "Sylvain Tenier"
date: "5 juin 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the file and removing null characters

```{r file load, cache=TRUE}
blogsConn <- file("./final/en_US/en_US.blogs.txt","r")
newsConn <- file("./final/en_US/en_US.news.txt","r")
twittConn <- file("./final/en_US/en_US.twitter.txt","r")
blogsLines <- readLines(blogsConn,n=-1,skipNul = TRUE)
newsLines <- readLines(newsConn,n=-1,skipNul = TRUE)
twittLines <- readLines(twittConn,n=-1,skipNul = TRUE)
close(blogsConn)
close(newsConn)
close(twittConn)
```

## Function to return words and isolated numbers from a line

```{r line words, cache=TRUE}
lineWords <- function(line){
    #replace all punctuation with space
    line <- gsub("[[:punct:]]"," ",line)
    #split by space
    tokens <- strsplit(line, split="[[:space:]]")[[1]]
    #find words with at least 2 letters
    #isWord <- sapply(tokens,function(tok){grepl("^[[:alpha:]][[:alpha:]]+$",tok)})
    isWord <- sapply(tokens,function(tok){grepl("^[[:alpha:]]+$",tok)})
    #find numbers
    isNumber <- sapply(tokens,function(tok){grepl("^[[:digit:]]+$",tok)})
    #return list of words and of numbers
    return(list(words=tokens[isWord], numbers=tokens[isNumber]))
}
```

## Function to count number of each word
```{r word count, cache=TRUE}
library(data.table)
occWords <- function(lines){
    # an environment is the most efficient hash table implementation in R
    occur <- new.env()
    for (i in 1:length(lines)){
        #get the list of words in a line
        words <- lineWords(lines[i])$words
        for(word in words){
            word <- tolower(word)
            #if this is the first occurence of the word, add it to the environment
            if(is.null(occur[[word]])){
                occur[[word]] <- 1
            #else increment the number of times the word is seen
            }else{
                occur[[word]] <- occur[[word]] +1
            }
        }
    }
    wordOccDf <- as.data.frame(unlist(as.list(occur)))
    setDT(wordOccDf,keep.rownames = TRUE)
    colnames(wordOccDf)<-c("word","occ")
    wordOccDf <- wordOccDf[order(-occ),]
}
```

## Frequency calculation

```{r frequency display, cache=TRUE}
blogsWords <- occWords(blogsLines)
newsWords <- occWords(newsLines)
twittWords <- occWords(twittLines)
```

## Top 10 table for each file

```{r top 10}
library(knitr)
kable(head(blogsWords,n=10))
kable(head(newsWords,n=10))
kable(head(twittWords,n=10))
```

## Histogram plot
```{r histogram}
library(ggplot2)
ggplot(blogsWords, aes(occ)) +
    geom_histogram(bins = 30, pad=TRUE) + 
    scale_y_log10()+
    scale_x_log10()

ggplot(newsWords, aes(occ)) +
    geom_histogram(bins = 20) + 
    scale_y_log10()+
    scale_x_log10()

ggplot(twittWords, aes(occ)) +
    geom_histogram(bins = 10) + 
    scale_y_log10()+
    scale_x_log10()
```
